INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (28, '이동영짱28', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (29, '이동영짱29', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (30, '이동영짱30', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (31, '이동영짱31', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (32, '이동영짱32', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (33, '이동영짱33', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (34, '이동영짱34', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (35, '이동영짱35', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (36, '이동영짱36', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (37, '이동영짱37', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (38, '이동영짱38', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (39, '이동영짱39', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (40, '이동영짱40', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (41, '이동영짱41', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (42, '이동영짱42', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (43, '이동영짱43', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (44, '이동영짱44', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (45, '이동영짱45', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (46, '이동영짱46', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (47, '이동영짱47', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (48, '이동영짱48', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (49, '이동영짱49', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (50, '이동영짱50', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (51, '이동영짱51', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (52, '이동영짱52', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (53, '이동영짱53', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (54, '이동영짱54', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (55, '이동영짱55', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (56, '이동영짱56', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (57, '이동영짱57', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (58, '이동영짱58', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (59, '이동영짱59', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (60, '이동영짱60', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (61, '이동영짱61', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (62, '이동영짱62', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (63, '이동영짱63', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (64, '이동영짱64', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (65, '이동영짱65', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (66, '이동영짱66', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (67, '이동영짱67', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (68, '이동영짱68', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (69, '이동영짱69', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (70, '이동영짱70', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (71, '이동영짱71', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (72, '이동영짱72', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (73, '이동영짱73', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (74, '이동영짱74', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (75, '이동영짱75', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (76, '이동영짱76', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (77, '이동영짱77', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (78, '이동영짱78', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (79, '이동영짱79', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (80, '이동영짱80', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (81, '이동영짱81', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (82, '이동영짱82', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (83, '이동영짱83', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (84, '이동영짱84', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (85, '이동영짱85', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (86, '이동영짱86', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (87, '이동영짱87', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (88, '이동영짱88', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (89, '이동영짱89', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (90, '이동영짱90', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (91, '이동영짱91', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (92, '이동영짱92', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (93, '이동영짱93', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (94, '이동영짱94', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (95, '이동영짱95', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (96, '이동영짱96', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (97, '이동영짱97', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (98, '이동영짱98', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (99, '이동영짱99', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (100, '이동영짱100', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (101, '이동영짱101', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (102, '이동영짱102', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (103, '이동영짱103', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (104, '이동영짱104', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (105, '이동영짱105', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (106, '이동영짱106', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (107, '이동영짱107', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (108, '이동영짱108', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (109, '이동영짱109', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (110, '이동영짱110', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (111, '이동영짱111', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (112, '이동영짱112', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (113, '이동영짱113', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (114, '이동영짱114', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (115, '이동영짱115', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (116, '이동영짱116', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (117, '이동영짱117', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (118, '이동영짱118', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (119, '이동영짱119', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (120, '이동영짱120', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (121, '이동영짱121', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (122, '이동영짱122', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (123, '이동영짱123', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (124, '이동영짱124', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (125, '이동영짱125', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (126, '이동영짱126', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (127, '이동영짱127', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (128, '이동영짱128', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);


commit;